### ISSUE TITLE
基礎前端版面設計

### ISSUE THREAD

**Issue by jurumi0823** [jurumi0823/DevOpsFinal#2]
設計專家設計前端版面

**Comment by aa08208247** [comment]
![螢幕擷取畫面 2024-11-06 222825](https://github.com/user-attachments/assets/2782a285-61fe-4dbc-90cf-b304dbc45e74)
![螢幕擷取畫面 2024-11-06 222859](https://github.com/user-attachments/assets/d1eb5b60-6705-4730-b8a5-2c6989290f1a)
